version: '3.1'

services:
  database:
    image: mysql
    container_name: drink_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '@dm1n#r00t'
      MYSQL_USER: fortics
      MYSQL_PASSWORD: kvallo2019
      MYSQL_DATABASE: drink
    volumes:
      - ./.db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: drink_app
    depends_on:
      - database
    ports:
      - "3333:3333"
    environment:
      DB_HOST: database
    volumes:
      - .:/var/www/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
